### ISSUE TITLE
Something wrong with connection on my machine

### ISSUE THREAD

**Issue by dimaty** [vashchenko/amberHashCalculator#1]
<img width="857" alt="screen shot 2019-01-14 at 12 36 22" src="https://user-images.githubusercontent.com/3091393/51108141-cde2d000-17f9-11e9-8cc3-2dd4aa23ba50.png">

Do you have this issue?

**Comment by vashchenko** [comment]
Well, now we know how garbage NSError looks like.

**Comment by vashchenko** [comment]
Fixed in https://github.com/vashchenko/amberHashCalculator/commit/eedd846a21c676e8abda74a6272f5d8f7c365905
